BOTO3_FSX = "fsx"

# provisioning lambda property names
DEFAULT_FSX_PARTITION_SIZE = 1200
PARTITION_SIZE = "partitionSize"
S3_BUCKET_IMPORT_URL = "S3_BUCKET_IMPORT_URL"
S3_BUCKET_EXPORT_URL = "S3_BUCKET_EXPORT_URL"
FSX_SG_ID = "FSX_SG_ID"
FSX_SUBNET_ID = "FSX_SUBNET_ID"

# payload property names
FILESYSTEM_ID = "fsxFilesystemId"
FILESYSTEM_DNS_NAME = "fsxFilesystemDnsName"
FILESYSTEM_MOUNT_NAME = "fsxFilesystemMountName"
FILESYSTEM_LIFECYCLE = "fsxFilesystemLifecycle"
ITEMS = "items"
PAYLOAD = "Payload"

# fsx api response property names
FILESYSTEM_PROPERTY = "FileSystem"
FILESYSTEM_ID_PROPERTY = "FileSystemId"
DNS_NAME_PROPERTY = "DNSName"
LUSTRE_CONFIG_PROPERTY = "LustreConfiguration"
MOUNT_NAME_PROPERTY = "MountName"
LIFECYCLE_PROPERTY = "Lifecycle"
FILESYSTEMS_PROPERTY = "FileSystems"

LUSTRE_FILESYSTEM_TYPE = "LUSTRE"
STORAGE_TYPE = "SSD"
LUSTRE_DEPLOYMENT_TYPE = "SCRATCH_2"
LZ4_DATA_COMPRESSION_TYPE = "LZ4"

IMPORT_PATH = "ImportPath"
EXPORT_PATH = "ExportPath"
DEPLOYMENT_TYPE = "DeploymentType"
DATA_COMPRESSION_TYPE = "DataCompressionType"
