BOTO3_FSX = "fsx"
BOTO3_CLOUDWATCH = "cloudwatch"

FILESYSTEM_ID = "fsxFilesystemId"
FILESYSTEM_LIFECYCLE = "fsxFilesystemLifecycle"
PAYLOAD = "Payload"
PARAMETERS = "Parameters"
OUTPUT = "Output"

# fsx api response property names
FILESYSTEMS_PROPERTY = "FileSystems"
LIFECYCLE_PROPERTY = "Lifecycle"
AVAILABLE = "AVAILABLE"

# fsx alarm properties
FX_PROVISION_ALARM_EVALUATION_PERIODS = "FX_PROVISION_ALARM_EVALUATION_PERIODS"
FX_PROVISION_ALARM_THRESHOLD = "FX_PROVISION_ALARM_THRESHOLD"
FX_PROVISION_ALARM_PERIOD = "FX_PROVISION_ALARM_PERIOD"
FX_PROVISION_ALARM_STATISTIC = "FX_PROVISION_ALARM_STATISTIC"
CW_ALARM_TOPIC = "CW_ALARM_TOPIC"

METRIC_NAME = "FreeDataStorageCapacity"
METRIC_NAMESPACE = "AWS/FSx"
METRIC_COMPARISON_OPERATOR = "LessThanOrEqualToThreshold"
NAME = "Name"
VALUE = "Value"
